### ISSUE TITLE
Webui not working?

### ISSUE THREAD

**Issue by BenPi-Ross** [thespad/docker-py-kms#31]
Hello!

In the Readme.md you state the following about the webui :
> Webui is accessible at http://SERVERIP:PORT
> 
> More info at [py-kms](https://github.com/Py-KMS-Organization/py-kms).

So I tried adding the port 8080:8080 as a docker configuration parameter (-p 8080:8080), but the webui is not accessible after the creation of the docker.

Is there something I'm missing?

Thanks!

**Comment by thespad** [comment]
That's an oversight on my part. Originally the image was based on the "full" upstream version which has an sqlite database and webui to show activation stats, but it made the container much bigger and (IMO) adds very little value, so I switched to the lighter image but forgot up to update the readme.

**Comment by BenPi-Ross** [comment]
Okay, thanks!
